### ISSUE TITLE
Trouble getting it run in Angular 4.x

### ISSUE THREAD

**Issue by gamefundas** [misha130/ngx-drag-and-drop-lists#1]
I was facing strange compilation errors when trying to get this run in Angular 4.x
Do you have a working version of this?

**Comment by misha130** [comment]
A compilation error?
I had no problem installing it on 4.1 and am running it right now on 4.1

Let me give you an example of how I use it right now:


```
 <div class="report-chart-list flex center-center"
        [dndList]="{
                disabled:dashboard.locked,
                effectAllowed: 'move',
                allowedTypes: ['item','type']}"
        [dndModel]="layout.reports"
        *ngFor="let layout of dashboard.layouts;let i = index;">
        <op-report (mousedown)="setActiveReport(report)"
          *ngFor="let report of layout.reports;let j = index;"
          [dndType]="'item'"
          (dndMoved)="removeItemDrag(layout, report)"
          [dndDragDisabled]="dashboard.locked"
          [dndDraggable]="{draggable:!dashboard.locked, effectAllowed:'move'}"
          [dndObject]="report"
          [dndList]="{
                disabled:dashboard.locked,
                effectAllowed: 'move',
                allowedTypes: ['type']}"
          (dndDrop)="setType($event,report)"
          [dndModel]="report.types">
        </op-report>
      </div>
```

Its an example of a list of items where the dndObject is also a dndList at the same time.

**Comment by gamefundas** [comment]
I tried running the demo and got a runtime template error,

Uncaught Error: Template parse errors:
Parser Error: Unexpected token '}' at column 25 in [nested.selected === item}] in ng:///AppModule/AppComponent.html@108:12 (" (dndMoved)="list.splice($index, 1)"
            (dndSelected)="nested.selected = item"
            [ERROR ->][class.selected]="nested.selected === item}">
            <div class="item">Item {{item.id}}</div>
  "): ng:///AppModule/AppComponent.html@108:12
Parser Error: Unexpected token '}' at column 25 in [nested.selected === item}] in ng:///AppModule/AppComponent.html@108:12 ("
        <ul [dndModel]="list"
          [dndList]>
          [ERROR ->]<li *ngFor="let item of list"
            [dndObject]="item"
            [dndDraggable]="{draggable:t"): ng:///AppModule/AppComponent.html@103:10, Directive DndDraggable
Parser Error: Unexpected token '}' at column 25 in [nested.selected === item}] in ng:///AppModule/AppComponent.html@108:12 ("
        <ul [dndModel]="list"
          [dndList]>
          [ERROR ->]<li *ngFor="let item of list"
            [dndObject]="item"
            [dndDraggable]="{draggable:t"): ng:///AppModule/AppComponent.html@103:10, Directive

**Comment by gamefundas** [comment]
Fixed by removing the braces from following line in app.component.html 
[class.selected]="nested.selected === item">

But now have another error 
AppComponent.html:42 ERROR TypeError: Cannot read property 'columns' of undefined
    at Object.eval [as updateDirectives] (AppComponent.html:101)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13056)
    at checkAndUpdateView (core.es5.js:12236)
    at callViewAction (core.es5.js:12601)
    at execComponentViewsAction (core.es5.js:12533)
    at checkAndUpdateView (core.es5.js:12242)
    at callWithDebugContext (core.es5.js:13456)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (core.es5.js:12996)
    at ViewRef_.webpackJsonp.../../../core/@angular/core.es5.js.ViewRef_.detectChanges (core.es5.js:10167)
    at core.es5.js:4805

It appear in the following line "typedLists" is undefined.
<div *ngFor="let list of typedLists"

I cloned this project to try out the demo. Am I doing something wrong. Dont see any releases so I am thinking the latest on this repo should have everything to make this run.

Thanks
Andy

**Comment by misha130** [comment]
I fixed it by removing it and pushed.
I took the demo from here:
https://github.com/marceljuenemann/angular-drag-and-drop-lists/blob/16f88b74359c5b5088b3b89e6f9b4fb6bace8fe9/demo/nested/nested.html

So it might have some irrelevant things (maybe irrelevant), I'll rewrite the demo on the weekend and redesign it.
Thanks

**Comment by gamefundas** [comment]
Thanks @misha130 I had to do something similar to get it working.
Now trying to get the multi-select example working as thats my primary goal. Hope you had a chance with that example.

**Comment by gamefundas** [comment]
Multi select example might need some work I guess. My knowledge of ngx is limited, still figuring it out. Let me know if you sort our the example before me. Thx.
