### ISSUE TITLE
Keep reference to same object vs cloning it

### ISSUE THREAD

**Issue by tomgruszowski** [misha130/ngx-drag-and-drop-lists#10]
Is it possible to keep a reference to the original object being dragged?

**Comment by johntdowney** [comment]
I'm new to Angular 2+, so I can't be certain, but having looked a bit through this library's innards, I suspect it might be the eventemitter that's cloning it.  For now, you can get around it by using IDs and some helper methods to get the original object yourself.

e.g.

`<li *ngFor="let obj of objs; let i = index;" [dndObject]="{object_id: obj.id, index: i}>{{objStuff}}</li>`

And then just make a findObjectById(id) method you can call to convert the object given to you by this library.  It's a little more complex if you have a tree-like structure, but you can do the same thing, you'll just need to keep a reference to the root list node throughout the nested list so you can use it to do a dfs search for the object.

**Comment by tomgruszowski** [comment]
@johntdowney this is exactly what I'm doing; it becomes very obvious when you have a strongly typed class as the backing collection and look at the console to see a list of items with MyClass {} and then a simple object literal for the dragged item.
