### ISSUE TITLE
Is this library deprecated or still active?

### ISSUE THREAD

**Issue by Francisco-RP** [misha130/ngx-drag-and-drop-lists#116]
It's 2023 but I'm supporting an app built with Angular 9. It uses this library in quite a few places and I'm trying not to have to switch completely to a new library so I'm making it work with a few snags (see my other issues I've reported)

The last commit for this library was in Sept of 2021 along with the last release being v1.3.3 in the same month. (this is the version I'm using)

Curious if this library will is still going to be supported and if that support will include minor/patch updates to the current version so that I can still use it in Angular 9 

other options:

This might be a good replacement for others wondering
https://www.npmjs.com/package/ngx-drag-drop

Ideally I think this might be the best one but I tried it and found it didn't handle nested lists as easily. I think there's a way to do it but have to find that link
https://material.angular.io/cdk/drag-drop/overview
https://www.npmjs.com/package/@angular/cdk

**Comment by misha130** [comment]
Honestly, I didn't maintain it much because of lack of public interest. 

If there is interest I'll migrate to ng16 but it's not a very simple process since libraries are deployed differently since ng9

**Comment by ClaudioCas** [comment]
> Honestly, I didn't maintain it much because of lack of public interest.
> 
> If there is interest I'll migrate to ng16 but it's not a very simple process since libraries are deployed differently since ng9

Dear Misha130,
Your library is by far the best and most versatile I've found for Angular. I'm using it for a composer where I need to manage nested drag and drop and it works really well!
I hope that the development of the library continues and it is updated for the latest versions of Angular too!

**Comment by misha130** [comment]
Well I did update the version for 16/17/18 of angular. 
Will  keep an eye on for bugs

**Comment by ClaudioCas** [comment]
Thanks a lot!
