### ISSUE TITLE
Incorrect Index when ordering items within list

### ISSUE THREAD

**Issue by PsiOps** [misha130/ngx-drag-and-drop-lists#17]
When ordering items within a list, the dndInsert event sometimes reports the wrong index. This is due to a bug in how the placeholder index is calculated. I submitted a [PR](https://github.com/misha130/ngx-drag-and-drop-lists/pull/16) to fix this.

**Comment by misha130** [comment]
Uploaded a new version to npm and accepted PR.
Thanks
