### ISSUE TITLE
Angular 6 version w/rxjs6

### ISSUE THREAD

**Issue by tomgruszowski** [misha130/ngx-drag-and-drop-lists#18]
Please ...

```
npm install -g rxjs-tslint
rxjs-5-to-6-migrate -p src/tsconfig.app.json
```

rxjs-tslint is a great tool from the rxjs team to automatically migrate your project which uses RxJS 5 to RxJS 6.

**Comment by misha130** [comment]
But the library doesnt contain any dependencies.
Are you saying its still affected?

**Comment by tomgruszowski** [comment]
@misha130 it does, notably rxjs Subscription.

**Comment by WTIGER001** [comment]
Please update for Angular 6 and RxJS6

**Comment by misha130** [comment]
Right, done in 1.2.1
