### ISSUE TITLE
postinstall: `tsc` error in v1.1.9

### ISSUE THREAD

**Issue by tomgruszowski** [misha130/ngx-drag-and-drop-lists#19]
This seems to be a very recent change, cleaned out node_modules just in case, no luck

`
ngx-drag-and-drop-lists@1.1.9 postinstall: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ngx-drag-and-drop-lists@1.1.9 postinstall script
`

Angular CLI: 6.0.8
Node: 10.4.0
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.2.1
@angular/cli                      6.0.8
@angular/material                 6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

**Comment by majid701** [comment]
i'm also facing the same issue.

Angular version: 5.0.0

**Comment by tncho** [comment]
Same error happening here with Angular 5.2.0 & Typescript 2.6.2 .

**Comment by cannontechnology** [comment]
Same error here Typescript 2.9.2 & Angular 6.0.6.  I'm dead in the water.

**Comment by cannontechnology** [comment]
Does anyone have a work around for this?  Also has anyone looked into ngx-dnd and know the pros/cons of each?

**Comment by tomgruszowski** [comment]
@cannontechnology, as with many packages that still haven't been updated to ng6, just take the code, and pop it into your app (contents of master/src). It's literally copy paste, obviously remove when library gets updated. I realize you likely don't want to do this, but it's pretty frustrating waiting for people to update their libraries sometimes (not just this one specifically), some even have pull requests and still nothing.

**Comment by misha130** [comment]
1.2.1 updated to ng6
