### ISSUE TITLE
dndDrop return value is ignored

### ISSUE THREAD

**Issue by igor-y** [misha130/ngx-drag-and-drop-lists#2]
https://github.com/misha130/ngx-drag-and-drop-lists/blob/ea00fcd491a039dc44df98023452228b101ae44f/src/directives/dnd-list.ts#L163

please add assign statement:

data = this.invokeCallback(this.dndDrop, event, dropEffect, itemType, index, data);

**Comment by chnakamura** [comment]
I don't think that this will work `invokeCallback()` returns `undefined`, so this will cause `stopDragOver()` to always be called.
