### ISSUE TITLE
Can't resolve 'rxjs/Subject'

### ISSUE THREAD

**Issue by chnakamura** [misha130/ngx-drag-and-drop-lists#20]
When I tried to run `ng serve` I got the error `Can't resolve 'rxjs/Subject'`. By changing `import { Subject } from 'rxjs/Subject';` to `import { Subject } from 'rxjs';` in `dnd-list.d.ts` and `dnd-list.js` I was able to fix the error.

**Comment by tomgruszowski** [comment]
This hasn't been updated for rxjs v6 yet, use rxjs-compat package or if you don't want to bloat your app, copy this entire lib into your project until it's updated.
