### ISSUE TITLE
Drop does not insert at placeholder if container object creates nested element

### ISSUE THREAD

**Issue by kevinjsmith** [misha130/ngx-drag-and-drop-lists#23]
In this [example](https://plnkr.co/edit/APnQ1AjKuxsIGPfFkXxj) drag over Container1, and then try to drag Container2 above Container1 Subcontainer. Container2, does not drop where the placeholder shows.

Drag Container2 here:
![drag-container](https://user-images.githubusercontent.com/34697816/42140817-8f980840-7d69-11e8-8486-5ee9958f40ca.PNG)

After the drop, it's not where it should be:
![drop-container](https://user-images.githubusercontent.com/34697816/42140820-94980bf6-7d69-11e8-8a9f-6d6e7da10f9f.PNG)

This is because the getPlaceholderIndex method finds the index of the placeholder among the container's children elements. But the insert happens agains the dndModel, which won't account for any nested elements the parent object created. Thus the index for where to splice the dropped element is wrong.

![dnd-insert-bug](https://user-images.githubusercontent.com/34697816/42140723-7cbef838-7d68-11e8-8151-03330071c5d8.PNG)

These edits to the dnd-list handleDrop method seem to fix the issue in this case, although I'm not sure what ramifications this could have for others:

`

       // Invoke the callback, which can transform the transferredObject and even abort the drop.
        let index: number = this.getPlaceholderIndex();
        // create an offset to account for extra elements (including the placeholder element)
        let offset: number = this.nativeElement.children.length - 1 - this.dndModel.length;
        if (this.dndDrop) {
            this.invokeCallback(this.dndDrop, event, dropEffect, itemType, index, data);
            if (!data) return this.stopDragOver();
        }
        // The drop is definitely going to happen now, store the dropEffect.
        this.dragState.dropEffect = dropEffect;
        if (!ignoreDataTransfer) {
            event.dataTransfer.dropEffect = dropEffect;
        }

        // Insert the object into the array, unless dnd-drop took care of that (returned true).
        if (data !== true) {
			//use the offset to create an insertionPoint
		    let insertionPoint = index - offset;
            if (insertionPoint < 0) {
                insertionPoint = 0
            }
            this.dndModel.splice(insertionPoint, 0, data);
        }
        this.invokeCallback(this.dndInserted, event, dropEffect, itemType, index, data);
`

**Comment by misha130** [comment]
I could not find fault with it, so I included it on 1.2.2.
Thank you for your contribution
