### ISSUE TITLE
In IE11, ngx-drag-and-drop-lists is not working

### ISSUE THREAD

**Issue by ArunSiddu** [misha130/ngx-drag-and-drop-lists#24]
I'm working on Angular 5 project, where I using the **ngx-drag-and-drop-lists** plugin. Its is working fine in the  chrome browser, but in IE11 getting the below error.,
**"TypeError: Object doesn't support property or method 'remove'**

How to fix this issue?

**Comment by kevinjsmith** [comment]
Try putting the code referenced here in the polyfill.ts file:
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove

**Comment by ArunSiddu** [comment]
Yeah, After implementing the referred function in polyfill.ts its working fine.
Thank you @kevinjsmith
