### ISSUE TITLE
Source Element Missing on Copy

### ISSUE THREAD

**Issue by kevinjsmith** [misha130/ngx-drag-and-drop-lists#27]
When an item is set to copy, the source element disappears from the screen, and is readded once the drop operation completes. This did not happen in version 1.1.7. Here's an example from the demo:

![dnd-copy](https://user-images.githubusercontent.com/34697816/43017497-f6ee5100-8c1b-11e8-9ec1-fc7d7f5312be.png)

**Comment by misha130** [comment]
Fixed this in 1.2.5
See https://github.com/misha130/ngx-drag-and-drop-lists/commit/4d20625776ba9a0603ffbc18607e6809101eac6d
Thanks for letting me know!
