### ISSUE TITLE
List item disappears if it's dragged and dropped over another

### ISSUE THREAD

**Issue by wexi79** [misha130/ngx-drag-and-drop-lists#36]
For some reason if I drag and drop a list item i a way that the dropped item is overlappin above another item, the list item disappears. If I drop the item without overlapping another, this does not happen. 

Any thoughts why this happens?

**Comment by wexi79** [comment]
Hm, seems like moving the item inside the list does something funny with the index. Moving the item all the way down on a list with 5 items (indexes 0-4) results in the last item having an index of 5 instead of 4. Moving the item back up shifts the indexes as expected but the first item now has an index of 1.

**Comment by annadiVreddy** [comment]
> Hm, seems like moving the item inside the list does something funny with the index. Moving the item all the way down on a list with 5 items (indexes 0-4) results in the last item having an index of 5 instead of 4. Moving the item back up shifts the indexes as expected but the first item now has an index of 1.

I'm facing the same issue. Were you able to resolve this issue?

**Comment by mahsaml90** [comment]
I'm facing the same issue

**Comment by JonathanDuclos** [comment]
Facing the same
