### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by anandhuajayakumar** [misha130/ngx-drag-and-drop-lists#38]
the npm install ngx-drag-and-drop-lists command fails.
npm i ngx-drag-and-drop-lists

> ngx-drag-and-drop-lists@1.2.5 postinstall C:\Users\anand\Desktop\tmaasapp\node_modules\ngx-drag-and-drop-lists
> tsc
> 
> ../@types/jasmine/index.d.ts(138,47): error TS1005: ';' expected.
> ../@types/jasmine/index.d.ts(138,90): error TS1005: '(' expected.
> ../@types/jasmine/index.d.ts(138,104): error TS1005: ']' expected.
> ../@types/jasmine/index.d.ts(138,112): error TS1005: ',' expected.
> ../@types/jasmine/index.d.ts(138,113): error TS1136: Property assignment expected.
> ../@types/jasmine/index.d.ts(138,121): error TS1005: ')' expected.
> ../@types/jasmine/index.d.ts(138,147): error TS1005: '(' expected.
> ../@types/jasmine/index.d.ts(138,162): error TS1005: ']' expected.
> ../@types/jasmine/index.d.ts(138,163): error TS1005: ',' expected.
> ../@types/jasmine/index.d.ts(138,164): error TS1136: Property assignment expected.
> ../@types/jasmine/index.d.ts(138,165): error TS1136: Property assignment expected.
> ../@types/jasmine/index.d.ts(138,179): error TS1005: ',' expected.
> ../@types/jasmine/index.d.ts(138,183): error TS1005: ':' expected.
> ../@types/jasmine/index.d.ts(138,208): error TS1005: '{' expected.
> ../@types/jasmine/index.d.ts(138,217): error TS1005: ':' expected.
> ../@types/jasmine/index.d.ts(138,222): error TS1005: ',' expected.
> ../@types/jasmine/index.d.ts(138,227): error TS1005: ':' expected.
> ../@types/jasmine/index.d.ts(138,228): error TS1109: Expression expected.
> ../@types/jasmine/index.d.ts(138,230): error TS1005: ')' expected.
> npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! ngx-drag-and-drop-lists@1.2.5 postinstall: `tsc`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the ngx-drag-and-drop-lists@1.2.5 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\anand\AppData\Roaming\npm-cache\_logs\2018-11-06T09_27_50_892Z-debug.log

**Comment by ghernandez81** [comment]
i have the same problem is there any update on this ?

**Comment by pdemilly** [comment]
this is the error I get when trying to install it

```
verbose stack Error: ngx-drag-and-drop-lists@1.2.5 postinstall: `tsc`
869 verbose stack Exit status 2
869 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
869 verbose stack     at emitTwo (events.js:126:13)
869 verbose stack     at EventEmitter.emit (events.js:214:7)
869 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
869 verbose stack     at emitTwo (events.js:126:13)
869 verbose stack     at ChildProcess.emit (events.js:214:7)
869 verbose stack     at maybeClose (internal/child_process.js:925:16)
869 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
870 verbose pkgid ngx-drag-and-drop-lists@1.2.5
871 verbose cwd /home/pascal/projects/agenda-fleet/agenda-fleet-admin
872 verbose Linux 4.15.0-43-generic
873 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
874 verbose node v8.9.1
875 verbose npm  v6.5.0
876 error code ELIFECYCLE
877 error errno 2
878 error ngx-drag-and-drop-lists@1.2.5 postinstall: `tsc`
878 error Exit status 2
879 error Failed at the ngx-drag-and-drop-lists@1.2.5 postinstall script.
879 error This is probably not a problem with npm. There is likely additional logging output above.
880 verbose exit [ 2, true ]
```

**Comment by johntdowney** [comment]
I ran into this issue, as well, but after starting with a fresh install of everything the issue did not pop up again, and I believe it was actually unrelated to this library, it was just appearing to.  Try it yourself by generating a new angular project and adding this to your package.json.

**Comment by shinchan305** [comment]
Having the same issue.
Here is a peek at my package.json

  "dependencies": {
    "@angular/animations": "6.0.0",
    "@angular/common": "6.0.0",
    "@angular/compiler": "6.0.0",
    "@angular/core": "6.0.0",
    "@angular/forms": "6.0.0",
    "@angular/http": "6.0.0",
    "@angular/platform-browser": "6.0.0",
    "@angular/platform-browser-dynamic": "6.0.0",
    "@angular/router": "6.0.0",
    "angular-2-dropdown-multiselect": "^1.9.0",
    "angular-user-idle": "^2.1.1",
    "core-js": "^2.4.1",
    "crypto-js": "^3.1.9-1",
    "file-saver": "^2.0.1",
    "mydatepicker": "^2.6.6",
    "ng2-completer": "^2.0.8",
    "ngx-cookie-service": "^2.1.0",
    "ngx-pagination": "^3.2.1",
    "ngx-drag-and-drop-lists": "^1.2.5",
    "rxjs": "6.0.0",
    "rxjs-compat": "^6.0.0-rc.0",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "^6.0.0",
    "@angular/compiler-cli": "6.0.0",
    "@angular/language-service": "6.0.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "^2.7.2"
  }
}

**Comment by holotrek** [comment]
I had the same issue, but it appears that this is due to the package having a postinstall script that just runs `tsc`. This means that if your project is not set up to compile correctly using just `tsc`, it will fail. I would suggest the author removes the postinstall script, as the compiled package is available in the dist already.

**Comment by cannontechnology** [comment]
Removed "postinstall" tsc in v1.3.3
