### ISSUE TITLE
Use Stackblitz for demo

### ISSUE THREAD

**Issue by FirstVertex** [misha130/ngx-drag-and-drop-lists#45]
I ported the demo to Stackblitz:

https://stackblitz.com/edit/ngx-drag-and-drop-lists

Suggest to change Official Demo to Stackblitz-based instead of Heroku-based, so users can fiddle around with the code and see live changes.

**Comment by misha130** [comment]
Thats pretty cool. Thanks.

**Comment by alexbateria** [comment]
awesome man, thanks!!
