### ISSUE TITLE
when using dndHandle attribute inside dndNoDrag ,there is an issue that drag elements gets disappear when dragged outside the element containing div 

### ISSUE THREAD

**Issue by albinjoseph1994** [misha130/ngx-drag-and-drop-lists#63]
when using dndHandle attribute inside dndNoDrag ,there is an issue that drag elements gets disappear when dragged outside the element containing div.When inspected the html code,it is shown that li element ie, dragged get property 'display: none'.

**Comment by JonathanDuclos** [comment]
Facing the same issue, I've tried change the CSS adding "posistion: relative" and other "style solutions" but nothing works to me.
