### ISSUE TITLE
not able to drag bottom to top (lower to upper)

### ISSUE THREAD

**Issue by Vaibhav2812** [misha130/ngx-drag-and-drop-lists#64]
Hi, 
I am using latest version of ngx-drag-drop-list. dragging from one column to another is happening even for the same column top to bottom is also happening.

the only problem is when I am dragging bottom to top widget positioning set is back original position below is my code

`   <ng-container *ngFor="let widgetColumn of widgetColumnList; let i = index">
             
        <div [dndList] [dndPlaceholder]="placeholder" [dndModel]="widgetColumn" >
            <div *ngFor="let widget of widgetColumn; let j = index"  
                [dndDraggable]
                [dndObject]="widget" (dndMoved)="removeMovedItem(j, widget, widgetColumn)">
                <ng-container [ngSwitch]="widget.type">
                     <div class="emr-patient-summary card">
                        <div class="emr-patient-summary-header d-flex align-items-center ">
                            <jhi-history-widget-header *ngSwitchCase="true" ></jhi-history-widget-header>
                         </div>
                                         
                    </div>
                </ng-container>
                           
             </div>
          </div>
    </ng-container>`

I am using Angular 8
Thanks

**Comment by ghost** [comment]
I have the same issue

**Comment by ghost** [comment]
using 1.1.7 version fixed the issue for me

**Comment by marcoagati** [comment]
I'm still having this issue. I'm using the latest version, 1.3.2.
If a try dropping the last item on the first, nothing happens, last item returns to its original position.

**Comment by dinakarreddy163** [comment]
<div class="col-md-3 csvcol4" [dndList] [dndPlaceholder]="placeholder" [dndModel]="erpColumns"
                style="height: 500px;overflow: scroll;position: relative;">
                <div class="col-md-12 csvcol4"
                  style="margin-top: -10px;padding-top: 9px;background-color: rgb(252, 248, 227);margin-bottom: 12px;">
                  ERP Fields </div>
                 **// Added row and i set ngFor for row also**
                  <div *ngFor="let item of erpColumns; let i = index" >
                  <div class="row" style="padding-left: 19px;padding-right: 15px;">
                <div class="col-md-12 csvcol4 mapCur"
                  [dndType]="'item'.type" (dndMoved)="removeItem(item, erpColumns)" (dblclick)="doubleClickErp(item,i)"
                  [ngStyle]="{color:item.isActive?'red':'black'}" [dndDraggable] [dndObject]="item">{{item.Name}}<br>
              </div>
                </div>
              </div>
              </div>



Try this code, may be it will work
