### ISSUE TITLE
angular 9 support

### ISSUE THREAD

**Issue by rahul-inno** [misha130/ngx-drag-and-drop-lists#65]
Modules are not working with angular 9 application. See below
ERROR in Failed to compile entry-point ngx-drag-and-drop-lists (main as commonjs) due to compilation errors:
node_modules/ngx-drag-and-drop-lists/module/module.js:17:35 - error NG1010: Value at position 0 in the NgModule.declarations of DndListModule is not a reference: [object Object]

17                     declarations: [DndDraggable, DndHandle, DndList, DndNoDrag],
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    
    ERROR in node_modules/ngx-drag-and-drop-lists/module/module.d.ts:17:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class
    
    17 export declare class DndListModule {
                            ~~~~~~~~~~~~~

**Comment by slegge** [comment]
I spent a few hours tracking this down, I was going to submit a fix, but it looks like the easiest solution for now is to disable ivy.  It doesn't look like it is going to be worth trying to fix, there is a more robust solution in @angular-cdk that is likely the way to go.

For the record, the workaround was:

`tsconfig.json:`

```
  "angularCompilerOptions": {
    "enableIvy": false
  }
```

**Comment by rahul-inno** [comment]
@slegge 
Hi,

thanks mate, I am trying this right now will let you know

**Comment by rahul-inno** [comment]
> I spent a few hours tracking this down, I was going to submit a fix, but it looks like the easiest solution for now is to disable ivy. It doesn't look like it is going to be worth trying to fix, there is a more robust solution in @angular-cdk that is likely the way to go.
> 
> For the record, the workaround was:
> 
> `tsconfig.json:`
> 
> ```
>   "angularCompilerOptions": {
>     "enableIvy": false
>   }
> ```

Yup its working now thanks.

**Comment by cannontechnology** [comment]
hey @slegge / @rahul-inno - did you add "enableIvy": false to the parent application or to ngx-drag-and-drop-lists to get around the Modules issue?
