### ISSUE TITLE
I’m getting an error on installing Ngx-drag-and-drop-lists.

### ISSUE THREAD

**Issue by akhtar030** [misha130/ngx-drag-and-drop-lists#76]
I'm using angular 6 and I need dynamic drag and drop for my project.

npm ERR! ngx-drag-and-drop-lists@1.3.2 postinstall: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ngx-drag-and-drop-lists@1.3.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Lospepes** [comment]
I had the same problem. I installed the previous version and added the changes on it manually.

**Comment by EmmadZahid** [comment]
Same here. I am thinking to fork this and remove the "postinstall" from package.json. then I will install from my own github repo.

**Comment by cannontechnology** [comment]
@EmmadZahid can you publish your repo?  I get the following error:
npm ERR! 404  '@emmadzahid/ngx-drag-and-drop-lists@^1.3.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'frontend'

**Comment by cannontechnology** [comment]
@EmmadZahid, @misha130 - I removed the "postinstall", how do I go about releasing v1.3.3 to npm?

**Comment by cannontechnology** [comment]
@akhtar030 @EmmadZahid @Lospepes - v.1.3.3 resolves the postinstall issue.
