### ISSUE TITLE
Angular 11 package install failed.

### ISSUE THREAD

**Issue by akhtar030** [misha130/ngx-drag-and-drop-lists#87]
While creating a new angular project I'm getting the below error.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: myapp@0.0.0
npm ERR! Found: jasmine-core@3.6.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\user\AppData\Local\npm-cache\eresolve-report.txt for a full report
× Package install failed, see above.
The Schematic workflow failed. See above.

**Comment by akhtar030** [comment]
Resolved by Updating angular to the latest version. The latest version of angular required npm 12 or higher version.

**Comment by cannontechnology** [comment]
@akhtar030 did you get it to install?  I'm still getting the "postinstall" tsc error.  I'm using ng 12 and npm 7.24.1

**Comment by cannontechnology** [comment]
v1.3.3 resolves the postinstall issue
