### ISSUE TITLE
Build Error coming after update angular version to 9 and ngx-drag-and-drop-lists@1.3.2

### ISSUE THREAD

**Issue by srinathreddy438** [misha130/ngx-drag-and-drop-lists#97]
Getting below build error
-----------------------------
This likely means that the library (ngx-drag-and-drop-lists) which declares DndListModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class DndListModule {

Trying to install 1.3.3
------------------------
when i do npm install getting below error
npm ERR! notarget No matching version found for ngx-drag-and-drop-lists@1.3.3

**Comment by cannontechnology** [comment]
@srinathreddy438  try now.

**Comment by cannontechnology** [comment]
Removed "postinstall" tsc in v1.3.3
