### ISSUE TITLE
is v1.3.3 released?

### ISSUE THREAD

**Issue by srinathreddy438** [misha130/ngx-drag-and-drop-lists#98]

**Comment by cannontechnology** [comment]
@srinathreddy438 v1.3.3 just removed postinstall tsc.  I'm having an issue with that after upgrading to ng12 as many others are as well.
@misha130 - How do I release to npm?

**Comment by misha130** [comment]
Email me (misha130@gmail.com) your npm username ill add you as a collaborator.

(alternatively you can release under your own name but its another package)

Then you simply compile and `npm publish ./dist' after changing package version.

**Comment by cannontechnology** [comment]
v1.3.3 is released
